testing SSR with NextJS
altsioma/otus-lessons pull request #34
Opened 2020-11-01 15:18 UTC by altsioma

2020-11-05 15:38 UTC, AntiHero requested changes
+ а в чём смысл приложения? график изменения курса валют? а как узнать какая валюта, какое значение и за какой период? было бы здорово, если бы ты подписал оси
+ убери пожалуйста в скриптах npx, его не нужно там использовать
+ кое где отсутствует типизация, это касается методов классов, а именно типов возвращаемых значений
+ увидел у тебя в коде `await localStorage.getItem("login");`, почему ты решил что getItem/set/remove это асинхронные методы?

2020-11-07 17:30 UTC, altsioma commented
* смысл был попробовать концепции реакт и сделать наработки для выпускного проекат, в проекте пробовал решить стек задач: асинхронная загрузка данных, отрисовка svg, динамические измененияв DOM, управляемые формы, hoc, redux, redux-saga. Спасибо за подсказку с лейблами, сделал только для оси валют, для дат - нужно доработать приложение, но это я уже сделаю в рамках выпускного проекта. Заодно пересмотрел и переосмыслил всю архитектуру и хочу учесть это так же в разработке будущего проекта.
* убрал, да это лишнее
* добавил
* это был копипаст с нашего учебного проекта, а там это было сделано для наглядности того, что в этих местах в реальности будут асинхронные методы, убрал у себя.

2020-11-09 10:37 UTC, AntiHero commented on package.json
>      "check": "npm run lint && npm run test",
npm run не надо писать в скриптах, просто пишешь `lint && test`

2020-11-09 11:14 UTC, AntiHero approved these changes

2020-11-09 11:14 UTC, AntiHero commented on src/pages/index.tsx
> +const App = () => {
забыл тип добавить

2020-11-09 12:45 UTC, merged